import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: {
    "google-adsense-account": "ca-pub-9096230429408950",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {process.env.NEXT_PUBLIC_ENABLE_ADS === "true" && (
          <>
            <Script id="gpt-loader" src="https://securepubads.g.doubleclick.net/tag/js/gpt.js" strategy="afterInteractive" />
            <Script id="gpt-init" strategy="afterInteractive">{`
              window.googletag = window.googletag || {cmd: []};
              window.googletag.cmd.push(function() {
                window.googletag.pubads().enableSingleRequest();
                window.googletag.enableServices();
              });
            `}</Script>
            <Script
              id="adsense-init"
              strategy="afterInteractive"
              src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-9096230429408950"
              crossOrigin="anonymous"
            />
          </>
        )}
        {children}
      </body>
    </html>
  );
}
